### ISSUE TITLE
Unsupported intent recogniton system (got conversation) on Hass

### ISSUE THREAD

**Issue by BlipRanger** [rhasspy/rhasspy-supervisor#7]
Hello, I just installed the latest version of Rhasspy on the latest version of Home Assistant (Hass) and I'm getting an error that looks like this:
```Starting up...
Using virtual environment at /usr/lib/rhasspy/.venv
DEBUG:rhasspysupervisor:Namespace(debug=True, docker_compose='', local_mqtt_port=12183, mosquitto_path='mosquitto', profile='en', supervisord_conf='supervisord.conf', system_profiles=None, user_profiles=PosixPath('/share/rhasspy/profiles'))
DEBUG:rhasspysupervisor:Loading profile en (user=/share/rhasspy/profiles, system=None)
DEBUG:rhasspyprofile.profile:Loading /usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/en/profile.json
DEBUG:rhasspyprofile.profile:Loading /share/rhasspy/profiles/en/profile.json
DEBUG:rhasspysupervisor:Generating supervisord conf
DEBUG:rhasspysupervisor:Microphone disabled (system=dummy)
DEBUG:rhasspysupervisor:Speakers disabled (system=hermes)
DEBUG:rhasspysupervisor:Speech to text disabled (system=dummy)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/rhasspy/rhasspy-supervisor/rhasspysupervisor/__main__.py", line 109, in <module>
    main()
  File "/usr/lib/rhasspy/rhasspy-supervisor/rhasspysupervisor/__main__.py", line 89, in main
    mosquitto_path=args.mosquitto_path,
  File "/usr/lib/rhasspy/rhasspy-supervisor/rhasspysupervisor/__init__.py", line 146, in profile_to_conf
    mqtt_password=mqtt_password,
  File "/usr/lib/rhasspy/rhasspy-supervisor/rhasspysupervisor/__init__.py", line 1747, in print_intent_recognition
    mqtt_password,
  File "/usr/lib/rhasspy/rhasspy-supervisor/rhasspysupervisor/__init__.py", line 1726, in get_intent_recognition
    raise ValueError(f"Unsupported intent recogniton system (got {intent_system})")
ValueError: Unsupported intent recogniton system (got conversation)
```
I have checked and confirmed that I don't have Conversations enabled in my config file (commented out currently). Any idea how to further troubleshoot this? Thanks!

**Comment by synesthesiam** [comment]
Check the `intent.system` property in your Rhasspy `profile.json` file. It should be `dummy` to be disabled or something like `fsticuffs`
